name: CI/CD — Deploy Todo App

on:
  push:
    branches: [main]
    paths:
      - 'projet-final/**'    # déclenché seulement si projet-final est modifié

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Vérification syntaxe Python
        run: python3 -m py_compile projet-final/services/api/app.py && echo "Syntax OK"

      - name: Rebuild et redéploiement
        working-directory: projet-final    # docker compose s'exécute depuis ce dossier
        run: docker compose up -d --build api

      - name: Vérification
        working-directory: projet-final
        run: docker compose ps
